"""baseline: full shiift schema, admin without role

Revision ID: abab7dbad43c
Revises: 
Create Date: 2026-07-05 21:41:20.693749

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'abab7dbad43c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('admin_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('professions',
    sa.Column('profession_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profession_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('profession_id')
    )
    op.create_table('states',
    sa.Column('state_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('state_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('state_id')
    )
    op.create_table('payments',
    sa.Column('payment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('amount_held', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('commission', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('worker_payout', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('paystack_reference', sa.String(length=100), nullable=True),
    sa.Column('payment_status', sa.Enum('pending', 'held', 'released', 'refunded'), nullable=False),
    sa.Column('paid_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('released_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('refunded_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], ),
    sa.PrimaryKeyConstraint('payment_id'),
    sa.UniqueConstraint('booking_id'),
    sa.UniqueConstraint('paystack_reference')
    )
    op.create_table('worker_locations',
    sa.Column('location_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=False),
    sa.Column('recorded_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.worker_id'], ),
    sa.PrimaryKeyConstraint('location_id')
    )

    # --- bookings: FIXED ORDER (drop constraints before the index they depend on) ---
    # --- also FIXED: booking_status enum was missing 'pending' ---
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('booking_status',
               existing_type=mysql.ENUM('confirmed', 'completed', 'cancelled'),
               type_=sa.Enum('pending', 'confirmed', 'cancelled', 'completed'),
               nullable=False,
               existing_server_default=sa.text("'confirmed'"))
        batch_op.alter_column('booked_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.drop_constraint(batch_op.f('fk_bookings_worker'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_bookings_shift'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('shift_id_UNIQUE'))
        batch_op.create_foreign_key(None, 'workers', ['worker_id'], ['worker_id'])
        batch_op.create_foreign_key(None, 'shifts', ['shift_id'], ['shift_id'])

    with op.batch_alter_table('facilities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('plan', sa.Enum('basic', 'standard', 'premium'), nullable=False))
        batch_op.add_column(sa.Column('plan_expires_at', sa.TIMESTAMP(), nullable=True))
        batch_op.add_column(sa.Column('cac_document', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('operating_licence_document', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('status', sa.Enum('pending', 'active', 'inactive', 'suspended'), nullable=False))
        batch_op.alter_column('facility_address',
               existing_type=mysql.VARCHAR(length=225),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('contact_phone',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.create_unique_constraint(None, ['contact_email'])
        batch_op.create_foreign_key(None, 'states', ['state_id'], ['state_id'])
        batch_op.drop_column('state')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.SmallInteger(),
               existing_nullable=False)
        batch_op.alter_column('reviewed_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.drop_constraint(batch_op.f('fk_reviews_booking'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'bookings', ['booking_id'], ['booking_id'])

    # --- shifts: FIXED ORDER (drop constraint before the index it depends on) ---
    # --- also FIXED: status enum was missing 'completed' ---
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profession_id', sa.Integer(), nullable=False))
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('open', 'filled', 'cancelled'),
               type_=sa.Enum('open', 'filled', 'cancelled', 'completed'),
               nullable=False,
               existing_server_default=sa.text("'open'"))
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.drop_constraint(batch_op.f('fk_shifts_facility'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('fk_shifts_facility_idx'))
        batch_op.create_foreign_key(None, 'professions', ['profession_id'], ['profession_id'])
        batch_op.create_foreign_key(None, 'facilities', ['facility_id'], ['facility_id'])

    # --- workers: FIXED: status enum was missing 'inactive' ---
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profession_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('state_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('bank_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('bank_account_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('bank_account_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('licence_document', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('qualification_document', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('id_document', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('passport_photo', sa.String(length=255), nullable=True))
        batch_op.alter_column('licence_number',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('pending', 'active', 'suspended'),
               type_=sa.Enum('pending', 'active', 'inactive', 'suspended'),
               nullable=False,
               existing_server_default=sa.text("'pending'"))
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.drop_index(batch_op.f('licence_number_UNIQUE'))
        batch_op.create_foreign_key(None, 'professions', ['profession_id'], ['profession_id'])
        batch_op.create_foreign_key(None, 'states', ['state_id'], ['state_id'])
        batch_op.drop_column('profession')

   
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profession', mysql.VARCHAR(length=50), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('licence_number_UNIQUE'), ['licence_number'], unique=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('pending', 'active', 'suspended'),
               nullable=True,
               existing_server_default=sa.text("'pending'"))
        batch_op.alter_column('licence_number',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('passport_photo')
        batch_op.drop_column('id_document')
        batch_op.drop_column('qualification_document')
        batch_op.drop_column('licence_document')
        batch_op.drop_column('bank_account_name')
        batch_op.drop_column('bank_account_number')
        batch_op.drop_column('bank_name')
        batch_op.drop_column('password')
        batch_op.drop_column('state_id')
        batch_op.drop_column('profession_id')

    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_shifts_facility'), 'facilities', ['facility_id'], ['facility_id'], onupdate='CASCADE')
        batch_op.create_index(batch_op.f('fk_shifts_facility_idx'), ['facility_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('open', 'filled', 'cancelled'),
               nullable=True,
               existing_server_default=sa.text("'open'"))
        batch_op.drop_column('profession_id')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_reviews_booking'), 'bookings', ['booking_id'], ['booking_id'], onupdate='CASCADE')
        batch_op.alter_column('reviewed_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('rating',
               existing_type=sa.SmallInteger(),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)

    with op.batch_alter_table('facilities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', mysql.VARCHAR(length=50), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('contact_phone',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('facility_address',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=225),
               existing_nullable=False)
        batch_op.drop_column('status')
        batch_op.drop_column('operating_licence_document')
        batch_op.drop_column('cac_document')
        batch_op.drop_column('plan_expires_at')
        batch_op.drop_column('plan')
        batch_op.drop_column('password')
        batch_op.drop_column('state_id')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_bookings_shift'), 'shifts', ['shift_id'], ['shift_id'], onupdate='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_bookings_worker'), 'workers', ['worker_id'], ['worker_id'], onupdate='CASCADE')
        batch_op.create_index(batch_op.f('shift_id_UNIQUE'), ['shift_id'], unique=True)
        batch_op.alter_column('booked_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('booking_status',
               existing_type=mysql.ENUM('confirmed', 'completed', 'cancelled'),
               nullable=True,
               existing_server_default=sa.text("'confirmed'"))

    op.drop_table('worker_locations')
    op.drop_table('payments')
    op.drop_table('states')
    op.drop_table('professions')
    op.drop_table('admins')
    # ### end Alembic commands ###
